// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRzlTzFtHiNnobV1pqI1IQV5dRVmILanY',
    appId: '1:143378829514:web:07d791d58b39110420a433',
    messagingSenderId: '143378829514',
    projectId: 'postfolio-app',
    authDomain: 'postfolio-app.firebaseapp.com',
    storageBucket: 'postfolio-app.firebasestorage.app',
    measurementId: 'G-R5JZBEK357',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQrhiPSNFfjdl1htRoLSgHa1wv7yB_YEM',
    appId: '1:143378829514:android:41d9df0d03361b6d20a433',
    messagingSenderId: '143378829514',
    projectId: 'postfolio-app',
    storageBucket: 'postfolio-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpaZ-4u82XcmYsvALV8Ef1su4YX-PC4mk',
    appId: '1:143378829514:ios:ede1817061a7a10320a433',
    messagingSenderId: '143378829514',
    projectId: 'postfolio-app',
    storageBucket: 'postfolio-app.firebasestorage.app',
    androidClientId: '143378829514-g9dcitgo5kd8r3kg68u4spgqc1l8h9uv.apps.googleusercontent.com',
    iosClientId: '143378829514-8no69brlamqrr9omemjjjv6k1b9jrtk1.apps.googleusercontent.com',
    iosBundleId: 'dev.darshanas.postfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpaZ-4u82XcmYsvALV8Ef1su4YX-PC4mk',
    appId: '1:143378829514:ios:ede1817061a7a10320a433',
    messagingSenderId: '143378829514',
    projectId: 'postfolio-app',
    storageBucket: 'postfolio-app.firebasestorage.app',
    androidClientId: '143378829514-g9dcitgo5kd8r3kg68u4spgqc1l8h9uv.apps.googleusercontent.com',
    iosClientId: '143378829514-8no69brlamqrr9omemjjjv6k1b9jrtk1.apps.googleusercontent.com',
    iosBundleId: 'dev.darshanas.postfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRzlTzFtHiNnobV1pqI1IQV5dRVmILanY',
    appId: '1:143378829514:web:ada2f101378be46220a433',
    messagingSenderId: '143378829514',
    projectId: 'postfolio-app',
    authDomain: 'postfolio-app.firebaseapp.com',
    storageBucket: 'postfolio-app.firebasestorage.app',
    measurementId: 'G-NG5X5NGZMG',
  );

}